# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'Hospital Management',
    'version': '1.0',
    'summary': 'Hospital Management Software',
    'sequence': 10,
    'description': """Hospital Management Software""",
    'category': 'Productivity',
    'license': 'LGPL-3',
    'website': 'https://www.osit.com.sa',
    'depends': ['sale',
                'mail',
                'report_xlsx'],
    'data': ['security/res_groups.xml',
             'security/ir.model.access.csv',
             'data/data.xml',
             'data/activity.xml',
             'wizard/create_appointment_view.xml',
             'wizard/appointment_report_view.xml',
             'wizard/all_patient_report_view.xml',
             'views/patient_view.xml',
             'views/appointment_view.xml',
             'views/sale.xml',
             'views/partner.xml',
             'views/kids_view.xml',
             'views/doctor_view.xml',
             'views/patient_gender_view.xml',
             'report/patient_card.xml',
             'report/appointment_details.xml',
             'report/all_patient_list.xml',
             'report/report.xml',
             'report/patient_details_template.xml'
             ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
